main/urls.py
from django.urls import path
from main.views import show_main
from main.views import show_main, create_product
from main.views import show_main, create_product, show_xml
from main.views import show_main, create_product, show_xml, show_json
from main.views import show_main, create_product, show_xml, show_json, show_xml_by_id, show_json_by_id
from main.views import register
from main.views import login_user
from main.views import logout_user
from main.views import edit_product
from main.views import delete_product
from main.views import show_about
from main.views import increment_item
from main.views import decrement_item
from main.views import get_product_json
from main.views import add_product_ajax
from main.views import create_product_flutter
from . import views


app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-product/<int:id>', edit_product, name='edit_product'),
    path('delete/<int:id>', delete_product, name='delete_product'),
    path('about/', show_about, name='about'),
    path('increment/<int:id>', increment_item, name='increment_item'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-product-ajax/', add_product_ajax, name='add_product_ajax'),
    path('create-product-ajax/', views.add_product_ajax, name='create_product_ajax'),
    path('get-items-ajax/', views.get_items_ajax, name='get_items_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),


]

pipboy/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path('auth/', include('authentication.urls'))

]

main/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=255)
    value = models.IntegerField()
    description = models.TextField(max_length=50)
    weight = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)    
    is_new = models.BooleanField(default=True)
    rarity = models.CharField(max_length=10)

main/forms.py
from django.forms import ModelForm
from main.models import Product

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name", "value", "description", "weight", "rarity"]

main/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from main.forms import ProductForm
from main.models import Product
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse



# Create your views here.
@login_required(login_url='/login')
def show_main(request):  
    items = Product.objects.filter(user=request.user).order_by('-id')  # Newest item first

    # Mark the newest item as is_new=True and all others as is_new=False
    if items:
        newest_item = items[0]
        newest_item.is_new = True
        newest_item.save()
        for item in items[1:]:
            item.is_new = False
            item.save()

    context = {
        'AppName': 'Pip-Boy!',
        'name': request.user.username,
        'class': 'PBP KI',
        'description': "From the innovative minds at Vault-Tec, we proudly present the Pip-Boy Inventory Manager, a cutting-edge web-based solution designed to enhance your post-apocalyptic survival experience. Just like its wrist-mounted predecessor, the Pip-Boy Inventory Manager offers seamless access to your crucial inventory data. Seamlessly navigate your stash of equipment, manage your consumables, and keep tabs on your quest progress, all from the comfort of your preferred device's web browser. Vault-Tec's commitment to user-friendly design ensures that you can effortlessly organize your post-apocalyptic life, whether it's keeping track of your precious bottle caps or maintaining your arsenal of weaponry. Surviving the wasteland has never been this organized, thanks to the Pip-Boy Inventory Manager—a technological marvel for the modern survivor.",
        'version': "Pip-Boy 3000 Mark IV Web Version",
        'releasedate': "2287",
        'items': items,
        'last_login': request.COOKIES.get('last_login'),
    }

    return render(request, 'main.html', context)

def create_product(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.is_new = True  # Set the is_new attribute to True for newly added items
        product.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_product.html", context)


def show_xml(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
        else:
            for field, errors in form.errors.items():
                for error in errors:
                    messages.error(request, f"{field.capitalize()}: {error}")
    
    else:
        form = UserCreationForm()
    
    context = {'form': form}
    return render(request, 'register.html', context)


def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def edit_product(request, id):
    # Get product by ID
    product = Product.objects.get(pk = id)

    # Set product as instance of form
    form = ProductForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        # Save the form and return to home page
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_product.html", context)

def delete_product(request, id):
    # Get data by ID
    product = Product.objects.get(pk=id)
    # Delete data
    product.delete()
    # Return to the main page
    return HttpResponseRedirect(reverse('main:show_main'))

def show_about(request):
    return render(request, 'about.html')

def increment_item(request, id):
    item = Product.objects.get(pk = id)
    item.amount += 1
    item.save()
    return HttpResponseRedirect(reverse('main:show_main'))

def decrement_item(request, id):
    item = Product.objects.get(pk = id)
    item.amount -= 1
    if item.amount <= 0:
        item.delete()
        return HttpResponseRedirect(reverse('main:show_main'))
    else:
        item.save()
        return HttpResponseRedirect(reverse('main:show_main'))


def get_product_json(request):
    items = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', items))

@csrf_exempt

def add_product_ajax(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        description = request.POST.get('description')
        value = request.POST.get('value')
        weight = request.POST.get('weight')
        
        # Perform any necessary validation or error handling here
        
        # Create a new Product instance
        new_product = Product(name=name, description=description, value=value, weight=weight, user=request.user)
        
        # Save the new product to the database
        new_product.save()
        
        # Return a success response
        return JsonResponse({'message': 'Product created successfully'}, status=201)
    
    # Handle GET requests or other cases
    return JsonResponse({'message': 'Invalid request method'}, status=400)

def get_items_ajax(request):
    items = Product.objects.filter(user=request.user)
    data = [{'pk': item.pk, 'name': item.name, 'is_new': item.is_new} for item in items]
    return JsonResponse(data, safe=False)

from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
import json
from .models import Product
from django.contrib.auth.decorators import login_required


@csrf_exempt
@login_required
def create_product_flutter(request):
    if request.method == 'POST':
        data = json.loads(request.body)

        new_product = Product.objects.create(
            user=request.user,
            name=data["name"],
            value=int(data["value"]),
            description=data["description"],
            weight=int(data["weight"]),
            is_new=bool(data["is_new"])
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/about.html
{% extends 'base.html' %}

{% block meta %}
    <title>About</title>
{% endblock meta %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/bgcolor.css' %}">
<style>
    .about {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        height: 100vh; /* Make the container take up the entire viewport height */
        font-family: monospace, Arial, sans-serif; /* Set the font to monospace with fallbacks */
        text-align: center;
    }

    .icon {
        width: 50px; /* Adjust the width of the icon as needed */
        height: 50px; /* Adjust the height of the icon as needed */
        margin-bottom: 20px; /* Adjust the margin as needed */
    }

    .app-info {
        max-width: 600px;
        color: #00ee00; /* Set text color to green */
    }

    /* Style for the "About" text */
    .about-text {
        margin-top: 20px;
        font-size: 14px; /* Reduce the font size */
        line-height: 1.5;
        color: #00ee00; /* Set text color to green */
    }

    /* Style for the version and release date */
    .version-info {
        margin-top: 20px;
        font-weight: bold;
        font-size: 12px; /* Reduce the font size */
        color: #00ee00; /* Set text color to green */
    }

    /* Style for the developer info */
    .developer-info {
        margin-top: 20px;
        font-style: italic;
        font-size: 12px; /* Reduce the font size */
        color: #00ee00; /* Set text color to green */
    }
    
    /* Adjust the header size */
    h1 {
        font-size: 20px; /* Reduce the font size */
        margin-top: 20px; /* Add margin to space out the headers */
        color: #00ee00; /* Set text color to green */
    }
</style>

<div class="about">
    <img src="{% static 'main/vaultboyicon.png' %}" alt="Icon" class="icon">
    
    <div class="app-info">
        <p><strong>"Pip-Boy! Inventory Manager Powered by Vault-Tec!"</strong></p>
    </div>
    
    <div class="app-info">
        <p><strong>Description:</strong></p>
        <p class="about-text">
            "From the innovative minds at Vault-Tec, we proudly present the Pip-Boy Inventory Manager, a cutting-edge web-based solution designed to enhance your post-apocalyptic survival experience. Just like its wrist-mounted predecessor, the Pip-Boy Inventory Manager offers seamless access to your crucial inventory data. Seamlessly navigate your stash of equipment, manage your consumables, and keep tabs on your quest progress, all from the comfort of your preferred device's web browser. Vault-Tec's commitment to user-friendly design ensures that you can effortlessly organize your post-apocalyptic life, whether it's keeping track of your precious bottle caps or maintaining your arsenal of weaponry. Surviving the wasteland has never been this organized, thanks to the Pip-Boy Inventory Manager—a technological marvel for the modern survivor."</p>
    </div>
    
    <div class="version-info">
        <p><strong>Version:</strong></p>
        <p>"Pip-Boy 3000 Mark IV Web Version"</p>
    </div>
    
    <div class="version-info">
        <p><strong>Release Date:</strong></p>
        <p>"2287"</p>
    </div>
    
    <div class="developer-info">
        <p><strong>Developed by:</strong></p>
        <p>"Muhammad Sakhran Thayyib of PBP KKI"</p>
    </div>
</div>

{% endblock content %}

main/templates/create_product.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/bgcolor.css' %}">
<style>
    body {
        font-family: 'ShareTech Mono', monospace, Arial, sans-serif;
        color: green; /* Set the default text color to green */
    }

    .login {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        height: 100vh;
    }

    .login h1 {
        color: #00ee00; /* Set the text color of h1 to green */
        font-size: 24px; /* Increase the font size of the title */
    }

    .login form {
        text-align: center;
    }

    .form-group {
        margin-bottom: 20px;
        position: relative;
    }

    input[type="text"],
    input[type="password"],
    input[type="number"], /* Use type="number" for numeric input fields */
    textarea { /* Apply styles to textareas for descriptions */
        background-color: lightgreen;
        width: 100%;
        padding: 10px;
        border: none;
        position: relative;
        color: black; /* Set the text color of input fields to black */
        font-family: 'ShareTech Mono', monospace, Arial, sans-serif; /* Use monospace font */
    }

    /* Remove borders from text input fields */
    input[type="text"],
    input[type="password"],
    input[type="number"] {
        border: none;
    }

    input[type="submit"] {
        background-color: #00ee00;
        color: black;
        font-weight: bold;
        padding: 10px 20px;
        border: none;
        cursor: pointer;
        margin-top: 20px; /* Add margin to the button for spacing */
    }

    input[type="submit"]:hover {
        background-color: darkgreen;
    }
</style>

<div class="login">
    <h1>Add New Item</h1>

    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            <input type="text" name="name" placeholder="Name"> <!-- Use placeholder text instead of label -->
        </div>

        <div class="form-group">
            <input type="number" name="value" placeholder="Value">
        </div>

        <div class="form-group">
            <textarea name="description" placeholder="Description" maxlength="50"></textarea> <!-- Use textarea for description -->
        </div>

        <div class="form-group">
            <input type="number" name="weight" placeholder="Weight">
        </div>

        <div class="form-group">
            <input type="submit" value="Add Item">
        </div>
    </form>
</div>

{% endblock %}

main/templates/edit_product.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/bgcolor.css' %}">
<style>
    body {
        font-family: 'ShareTech Mono', monospace, Arial, sans-serif;
        color: #00ee00; /* Set the default text color to green */
    }

    .login {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        height: 100vh;
    }

    .login h1 {
        color: #00ee00; /* Set the text color of h1 to green */
        font-size: 24px; /* Increase the font size of the title */
    }

    .login form {
        text-align: center;
    }

    .form-group {
        margin-bottom: 20px;
        position: relative;
    }

    input[type="text"],
    input[type="password"],
    input[type="number"], /* Use type="number" for numeric input fields */
    textarea { /* Apply styles to textareas for description */
        background-color: lightgreen;
        width: 100%;
        padding: 10px;
        border: none;
        position: relative;
        color: black; /* Set the inline text color to black */
        font-family: 'ShareTech Mono', monospace, Arial, sans-serif; /* Use monospace font */
    }

    /* Remove borders from text input fields */
    input[type="text"],
    input[type="password"],
    input[type="number"] {
        border: none;
    }

    /* Style for placeholder (ghosting) text */
    ::placeholder {
        color: 00ee00;
        font-family: 'ShareTech Mono', monospace, Arial, sans-serif;
    }

    input[type="submit"] {
        background-color: #00ee00;
        color: black;
        font-weight: bold;
        padding: 10px 20px;
        border: none;
        cursor: pointer;
        margin-top: 20px; /* Add margin to the button for spacing */
    }

    input[type="submit"]:hover {
        background-color: darkgreen;
    }
</style>

<div class="login">
    <h1>Edit Item</h1>

    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            <input type="text" name="{{ form.name.name }}" placeholder="Name" value="{{ form.name.value }}">
        </div>
        <div class="form-group">
            <input type="number" name="{{ form.value.name }}" placeholder="Value" value="{{ form.value.value }}">
        </div>
        <div class="form-group">
            <textarea name="{{ form.description.name }}" placeholder="Description" maxlength="50">{{ form.description.value }}</textarea>
        </div>
        <div class="form-group">
            <input type="number" name="{{ form.weight.name }}" placeholder="Weight" value="{{ form.weight.value }}">
        </div>

        <div class="form-group">
            <input type="submit" value="Edit Product">
        </div>
    </form>
</div>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/bgcolor.css' %}">
<style>
    .login {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        height: 100vh; /* Make the container take up the entire viewport height */
        font-family: monospace, Arial, sans-serif; /* Set the font to monospace with fallbacks */
    }

    .login form {
        text-align: center;
    }

    .form-group {
        margin-bottom: 20px;
    }

    .icon {
        width: 50px; /* Adjust the width of the icon as needed */
        height: 50px; /* Adjust the height of the icon as needed */
        margin-bottom: 20px; /* Adjust the margin as needed */
    }

    /* Style the Login button */
    .login_btn {
        background-color: #00ee00;
        color: black;
        font-weight: bold;
        padding: 10px 20px; /* Adjust padding as needed */
        border: none;
        cursor: pointer;
    }

    /* Hover effect for the Login button */
    .login_btn:hover {
        background-color: darkgreen; /* Change the color on hover if desired */
    }

    /* Center the placeholder text in input fields */
    input::placeholder {
        text-align: center;
    }

    /* Set the background color of input fields to light green */
    input[type="text"],
    input[type="password"] {
        background-color: lightgreen;
    }

    /* Keep the background color light green when input is focused */
    input[type="text"]:focus,
    input[type="password"]:focus {
        background-color: lightgreen;
    }

    /* Style for error messages */
    .error-message {
        color: red;
        font-weight: bold;
    }
</style>

<div class="login">
    {% load static %}
    <img src="{% static 'main/vaultboyicon.png' %}" alt="Icon" class="icon">
    <form method="POST" action="">
        {% csrf_token %}
        <div class="form-group">
            <input type="text" name="username" placeholder="Username" class="form-control">
        </div>

        <div class="form-group">
            <input type="password" name="password" placeholder="Password" class="form-control">
        </div>

        <div class="form-group">
            <button class="btn login_btn" type="submit">Login</button>
        </div>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li class="error-message">{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <p> <a href="{% url 'main:register' %}" style="color: #00ee00;">Create Account</a></p>
    
    <!-- Add the "About" hyperlink below the "Create Account" hyperlink -->
    <p> <a href="{% url 'main:about' %}" style="color: #00ee00;">About</a></p>
</div>

{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/bgcolor.css' %}">
<style>
    body {
        font-family: 'ShareTech Mono', monospace, Arial, sans-serif;
    }

    .login {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        height: 100vh;
    }

    .login form {
        text-align: center;
    }

    .form-group {
        margin-bottom: 20px;
        position: relative;
    }

    .icon {
        width: 50px;
        height: 50px;
        margin-bottom: 20px;
    }

    input[type="text"],
    input[type="password"] {
        background-color: lightgreen;
        width: 100%;
        padding: 10px;
        border: none;
        position: relative; /* Add relative positioning to the text fields */
    }

    .register_btn {
        background-color: #00ee00;
        color: black;
        font-weight: bold;
        padding: 10px 20px;
        border: none;
        cursor: pointer;
    }

    .register_btn:hover {
        background-color: darkgreen;
    }

    /* Style for error messages */
    .error-message {
        color: red;
        font-weight: bold;
    }

    /* Updated tooltip positioning for username and password */
    .form-group[data-tooltip]::after {
        content: attr(data-tooltip);
        position: absolute;
        background-color: rgba(0, 0, 0, 0.7);
        color: white;
        padding: 5px;
        border-radius: 5px;
        font-size: 12px;
        max-width: 1000px; /* Increase the maximum width of the tooltip */
        text-align: center;
        visibility: hidden;
        opacity: 0;
        transition: opacity 0.3s, visibility 0.3s;
    }

    /* Position the username tooltip on the right side of the text field */
    .username-tooltip::after {
        left: 100%; /* Position to the right of the text field */
        top: 50%; /* Vertically centered */
        transform: translateY(-50%);
    }

    /* Position the password tooltip on the right side of the text field */
    .password-tooltip::after {
        left: 100%; /* Position to the right of the text field */
        top: 50%; /* Vertically centered */
        transform: translateY(-50%);
    }

    .form-group:hover::after {
        visibility: visible;
        opacity: 1;
    }
</style>

<div class="login">
    <img src="{% static 'main/vaultboyicon.png' %}" alt="Icon" class="icon">
    <form method="POST" action="">
        {% csrf_token %}
        <div class="form-group username-tooltip" data-tooltip="Required: ≤ 150 characters, use only letters, digits, @/./+/-/_.">
            <input type="text" name="username" placeholder="Username" class="form-control">
        </div>

        <div class="form-group password-tooltip" data-tooltip="Ensure your password is not too similar to your personal info, 
        has at least 8 characters, avoids common choices, and isn't purely numeric.">
            <input type="password" name="password1" placeholder="Password" class="form-control">
        </div>

        <div class="form-group">
            <input type="password" name="password2" placeholder="Confirm Password" class="form-control">
        </div>

        <div class="form-group">
            <button class="btn register_btn" type="submit">Register</button>
        </div>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li class="{% if message.tags == 'success' %}success-message{% else %}error-message{% endif %}">{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
</div>

{% endblock content %}